#!/usr/bin/env php
<?php

	require_once 'vendor/autoload.php';

	$opts = getopt('b:');
	$birthDate = $opts['b'] ?? '1997-06-06';
	$days = new \GorAlex97\Dates\VagrantPhp($birthDate);
	$totalDays = $days->findTotalDays();

	echo $birthDate.' : '.$totalDays."\n";

?>
